# Simple workflow for deploying static content to GitHub Pages
name: hooui构建

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Deploy to GitHub Pages
        run: npm i pnpm -g && pnpm install --no-frozen-lockfile && pnpm docs:build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vitepress/dist

      - name: Install Serverless CLI
        run: npm install -g @serverless-devs/s
      - name: Serverless Config
        run: s config add --AccessKeyID ${{secrets.ACCESS_KEY_ID}} --AccessKeySecret ${{secrets.ACCESS_KEY_SECRET}} -a default -f
      - name: Prepare deployment directory
        run: |
          mkdir deploy
          cp -r docs/.vitepress/dist deploy/hooui
          cp -r .serverless/* deploy
      - name: Deploy to Aliyun Serverless
        run: s deploy -y --use-local
